import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";


const Signup = () => {
  const navigate = useNavigate();
  const [username, setUsername] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [role, setRole] = useState("admin");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const handleSignup = async (e) => {
    e.preventDefault();
  
    if (!username || !email || !password) {
      setError("All fields are required!");
      return;
    }
  
    if (password.length < 6) {
      setError("Password must be at least 6 characters long.");
      return;
    }
  
    setError(""); // Clear previous errors
  
    try {
      setLoading(true);
      
      // Instead of making an API call, store user data in localStorage
      const users = JSON.parse(localStorage.getItem("users") || "[]");
      
      // Check if email already exists
      if (users.some(user => user.email === email)) {
        throw new Error("Email already exists");
      }
      
      // Create a mock token (in real apps, this would be generated by the server)
      const mockToken = `token_${Date.now()}_${Math.random().toString(36).substring(2, 15)}`;
      
      // Create new user object
      const newUser = {
        id: Date.now(),
        username,
        email,
        password, // Note: In a real app, never store plain text passwords
        role,
        token: mockToken
      };
      
      // Add new user to users array
      users.push(newUser);
      
      // Save updated users array
      localStorage.setItem("users", JSON.stringify(users));
      
      // Store current user session info
      localStorage.setItem("token", mockToken);
      localStorage.setItem("userRole", role);
      localStorage.setItem("currentUser", JSON.stringify({
        id: newUser.id,
        username,
        email,
        role
      }));
      
      toast.success("Signup successful! Redirecting...");
      
      // Redirect based on role
      setTimeout(() => {
        if (role === "admin") {
          navigate("/admin");
        } else if (role === "executive") {
          navigate("/executive");
        } else {
          navigate("/user");
        }
      }, 2000);
      
    } catch (error) {
      console.error("Signup error:", error);
      toast.error(error.message || "Registration failed. Please try again.");
      setError(error.message || "Registration failed. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="container">
      <ToastContainer position="top-right" autoClose={3000} />
      <div className="background-box-1"></div>
      <div className="background-box-2"></div>

      <div className="form-container">
        <div className="left-box">
          <h2>WELCOME BACK!</h2>
          <p>Already have an account? Click below to log in.</p>
          <button className="switch-btn" onClick={() => navigate("/login")}>
            SIGN IN
          </button>
        </div>

        <div className="right-box">
          <h2>Create Account</h2>
          {error && <p className="error-message">{error}</p>}
          
          <p>or use your email account</p>
          <form onSubmit={handleSignup}>
            <input
              type="text"
              placeholder="Username"
              required
              value={username}
              onChange={(e) => setUsername(e.target.value)}
            />
            <input
              type="email"
              placeholder="Email"
              required
              value={email}
              onChange={(e) => setEmail(e.target.value)}
            />
            <input
              type="password"
              placeholder="Password"
              required
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />
            
            <select 
              value={role} 
              onChange={(e) => setRole(e.target.value)} 
              className="Role"
            >
              <option value="admin">Admin</option>
              <option value="executive">Executive</option>
              <option value="user">Team Lead</option>
            </select>

            <button type="submit" disabled={loading}>
              {loading ? "Signing up..." : "SIGN UP"}
            </button>
          </form>
        </div>
      </div>
    </div>
  );
};

export default Signup;